<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // $this->call(UsersTableSeeder::class);

        $now = date("Y-m-d H:i:s");

        DB::table("configuracoes")->insert([
            "coluna_ordena" => "valor",
            "direcao_ordena" => 'desc',
            "tempo_transicao" => "10000",
        ]);

        DB::table('grupos')->insert([
            ["descricao" => "Bovinos"],
            ["descricao" => "Suínos"],
            ["descricao" => "Aves"],
        ]);

        DB::table('unidades')->insert([
            ["descricao" => "KG"],
            ["descricao" => "UN"],
            ["descricao" => "Inteiro"],
        ]);

        DB::table('produtos')->insert([
            [
                "nome" => "FILE MIGNON",
                "grupo_id" => "1",
                "valor" => "39.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "nome" => "PICANHA",
                "grupo_id" => "1",
                "valor" => "39.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "nome" => "CONTRA-FILE",
                "grupo_id" => "1",
                "valor" => "32.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "nome" => "ALCATRA",
                "grupo_id" => "1",
                "valor" => "32.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "nome" => "COXÃO MOLE",
                "grupo_id" => "1",
                "valor" => "27.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "nome" => "PATINHO",
                "grupo_id" => "1",
                "valor" => "25.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "nome" => "MAMINHA",
                "grupo_id" => "1",
                "valor" => "26.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "nome" => "MAÇA DO PEITO",
                "grupo_id" => "1",
                "valor" => "17.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "nome" => "LAGARTO",
                "grupo_id" => "1",
                "valor" => "21.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "nome" => "COXÃO DURO",
                "grupo_id" => "1",
                "valor" => "21.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "nome" => "PALETA",
                "grupo_id" => "1",
                "valor" => "23.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "nome" => "PONTA DE AGULHA",
                "grupo_id" => "1",
                "valor" => "23.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "nome" => "FRALDINHA",
                "grupo_id" => "1",
                "valor" => "23.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "nome" => "MUSCULO",
                "grupo_id" => "1",
                "valor" => "17.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "nome" => "CAPA GROSSA",
                "grupo_id" => "1",
                "valor" => "18.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "nome" => "ACEM",
                "grupo_id" => "1",
                "valor" => "17.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "nome" => "LOMBÃO",
                "grupo_id" => "1",
                "valor" => "17.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],[
                "nome" => "CUPIM",
                "grupo_id" => "1",
                "valor" => "18.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],[
                "nome" => "COSTELA DE BOI TIRA",
                "grupo_id" => "1",
                "valor" => "11.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],[
                "nome" => "COSTELA DE BOI GAUCHA",
                "grupo_id" => "1",
                "valor" => "13.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],[
                "nome" => "ALMONDEGA",
                "grupo_id" => "1",
                "valor" => "19.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],[
                "nome" => "BIFE ROLE",
                "grupo_id" => "1",
                "valor" => "23.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],[
                "nome" => "FIGADO DE BOI",
                "grupo_id" => "1",
                "valor" => "15.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],[
                "nome" => "RABADA",
                "grupo_id" => "1",
                "valor" => "15.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "nome" => "CAPA DE COSTELA",
                "grupo_id" => "1",
                "valor" => "14.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "nome" => "LOMBO",
                "grupo_id" => "2",
                "valor" => "18.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "nome" => "PERNIL TRASEIRO",
                "grupo_id" => "2",
                "valor" => "16.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],[
                "nome" => "CABEÇA DE LOMBO",
                "grupo_id" => "2",
                "valor" => "17.99",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],[
                "nome" => "PERNIL DIANTEIRO PAZINHA",
                "grupo_id" => "2",
                "valor" => "15.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],[
                "nome" => "LINGUIÇA DE PERNIL",
                "grupo_id" => "2",
                "valor" => "18.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],[
                "nome" => "LINGUIÇA LOMBO + PIMENTA",
                "grupo_id" => "2",
                "valor" => "18.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],[
                "nome" => "LINGUIÇA CASEIRA PURA",
                "grupo_id" => "2",
                "valor" => "18.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],[
                "nome" => "COSTELINHA",
                "grupo_id" => "2",
                "valor" => "17.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],[
                "nome" => "LINGUIÇA CASEIRA",
                "grupo_id" => "2",
                "valor" => "18.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],[
                "nome" => "PANCETA",
                "grupo_id" => "2",
                "valor" => "15.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],[
                "nome" => "SUÂ",
                "grupo_id" => "2",
                "valor" => "10.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],[
                "nome" => "LINGUIÇA MISTA",
                "grupo_id" => "2",
                "valor" => "12.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],[
                "nome" => "PEZINHO",
                "grupo_id" => "2",
                "valor" => "9.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],[
                "nome" => "FUCINHO",
                "grupo_id" => "2",
                "valor" => "7.99",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],[
                "nome" => "BISTECA SUINA",
                "grupo_id" => "2",
                "valor" => "14.99",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "nome" => "FRANGO INTEIRO",
                "grupo_id" => "3",
                "valor" => "6.99",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "nome" => "COXINHA DA ASA",
                "grupo_id" => "3",
                "valor" => "12.49",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "nome" => "TULIPA DA ASA",
                "grupo_id" => "3",
                "valor" => "18.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],[
                "nome" => "FILÉ DE FRANGO",
                "grupo_id" => "3",
                "valor" => "11.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],[
                "nome" => "ASA DE FRANGO",
                "grupo_id" => "3",
                "valor" => "11.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],[
                "nome" => "COXA E SOBRECOXA",
                "grupo_id" => "3",
                "valor" => "12.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],[
                "nome" => "CORAÇÃO DE FRANGO",
                "grupo_id" => "3",
                "valor" => "21.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],[
                "nome" => "MOELA",
                "grupo_id" => "3",
                "valor" => "7.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],[
                "nome" => "PEITO COM OSSO",
                "grupo_id" => "3",
                "valor" => "8.90",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],
        ]);

        DB::table('promocoes')->insert([
            [
                "nome" => "MAÇA DO PEITO",
                "preco" => "17.90",
                "grupo_id" => "1",
                "imagem" => "",
                "unidade_id" => "1",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "nome" => "LAGARTO",
                "preco" => "21.90",
                "grupo_id" => "1",
                "imagem" => "",
                "unidade_id" => "1",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "nome" => "COXÃO DURO",
                "preco" => "21.90",
                "grupo_id" => "1",
                "imagem" => "",
                "unidade_id" => "1",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "nome" => "COSTELA DE BOI-TIRA",
                "preco" => "11.90",
                "grupo_id" => "2",
                "imagem" => "",
                "unidade_id" => "1",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "nome" => "CERVEJA PETRA",
                "preco" => "2.89",
                "grupo_id" => "2",
                "imagem" => "",
                "unidade_id" => "2",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "nome" => "FRANGO INTEIRO",
                "preco" => "6.99",
                "grupo_id" => "3",
                "imagem" => "",
                "unidade_id" => "1",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "nome" => "PROMOCAO",
                "preco" => "10.00",
                "grupo_id" => "1",
                "imagem" => "",
                "unidade_id" => "3",
                "status" => "1",
                "created_at" => $now,
                "updated_at" => $now,
            ],
        ]);
    }
}
